`timescale 1ns/1ps

import hestia_pkg::*;

// Core-only synthesis wrapper for paper-style resource accounting.
// It keeps functional ingress, egress, and DDR AXI ports, while leaving
// measurement/debug outputs internal so synthesis can trim counters.
module hestia_resource_core #(
  parameter int PORTS = 2,
  parameter int RANK_WIDTH = 6,
  parameter int SEQ_WIDTH = 16,
  parameter int PAYLOAD_WIDTH = 32,
  parameter int CELL_COUNT_WIDTH = 4,
  parameter int AXI_ADDR_WIDTH = 64,
  parameter int AXI_DATA_WIDTH = 512,
  parameter int AXI_ID_WIDTH = 4,
  parameter int SRAM_CELLS = 16,
  parameter int BATCH_SIZE = 8,
  parameter int BATCH_SLOTS = 16,
  parameter int PACKET_SLOTS = 32,
  parameter int BBQ_BITMAP_WIDTH = 8,
  parameter int POLICY_MODE = -1,
  parameter int POLICY_ALPHA_SHIFT = 0,
  parameter int POLICY_ALPHA_SHIFT_WIDTH = 4,
  parameter bit EXTERNAL_METADATA = 1'b0,
  parameter bit ENABLE_DDR_META_CHECK = 1'b0,
  parameter logic [AXI_ADDR_WIDTH-1:0] DDR_BASE_ADDR = 64'h0,
  localparam int PORT_W = (PORTS <= 2) ? 1 : $clog2(PORTS),
  localparam int AXI_KEEP_WIDTH = AXI_DATA_WIDTH / 8
) (
  input  logic                              clk,
  input  logic                              resetn,
  input  logic                              enable,
  input  logic [15:0]                       cfg_swap_in_threshold,
  input  logic [15:0]                       cfg_swap_out_threshold,

  input  logic                              s_pkt_valid,
  output logic                              s_pkt_ready,
  input  logic [PORT_W-1:0]                 s_pkt_port,
  input  logic [RANK_WIDTH-1:0]             s_pkt_rank,
  input  logic [SEQ_WIDTH-1:0]              s_pkt_seq,
  input  logic [CELL_COUNT_WIDTH-1:0]       s_pkt_cell_count,
  input  logic [PAYLOAD_WIDTH-1:0]          s_pkt_payload,

  input  logic [PORTS-1:0]                  dequeue_enable,
  output logic [PORTS-1:0]                  m_pkt_valid,
  input  logic [PORTS-1:0]                  m_pkt_ready,
  output logic [PORTS*RANK_WIDTH-1:0]       m_pkt_rank,
  output logic [PORTS*SEQ_WIDTH-1:0]        m_pkt_seq,
  output logic [PORTS*CELL_COUNT_WIDTH-1:0] m_pkt_cell_count,
  output logic [PORTS*PAYLOAD_WIDTH-1:0]    m_pkt_payload,

  output logic [AXI_ID_WIDTH-1:0]           m_axi_awid,
  output logic [AXI_ADDR_WIDTH-1:0]         m_axi_awaddr,
  output logic [7:0]                        m_axi_awlen,
  output logic [2:0]                        m_axi_awsize,
  output logic [1:0]                        m_axi_awburst,
  output logic                              m_axi_awlock,
  output logic [3:0]                        m_axi_awcache,
  output logic [2:0]                        m_axi_awprot,
  output logic [3:0]                        m_axi_awqos,
  output logic                              m_axi_awvalid,
  input  logic                              m_axi_awready,
  output logic [AXI_DATA_WIDTH-1:0]         m_axi_wdata,
  output logic [AXI_KEEP_WIDTH-1:0]         m_axi_wstrb,
  output logic                              m_axi_wlast,
  output logic                              m_axi_wvalid,
  input  logic                              m_axi_wready,
  input  logic [AXI_ID_WIDTH-1:0]           m_axi_bid,
  input  logic [1:0]                        m_axi_bresp,
  input  logic                              m_axi_bvalid,
  output logic                              m_axi_bready,
  output logic [AXI_ID_WIDTH-1:0]           m_axi_arid,
  output logic [AXI_ADDR_WIDTH-1:0]         m_axi_araddr,
  output logic [7:0]                        m_axi_arlen,
  output logic [2:0]                        m_axi_arsize,
  output logic [1:0]                        m_axi_arburst,
  output logic                              m_axi_arlock,
  output logic [3:0]                        m_axi_arcache,
  output logic [2:0]                        m_axi_arprot,
  output logic [3:0]                        m_axi_arqos,
  output logic                              m_axi_arvalid,
  input  logic                              m_axi_arready,
  input  logic [AXI_ID_WIDTH-1:0]           m_axi_rid,
  input  logic [AXI_DATA_WIDTH-1:0]         m_axi_rdata,
  input  logic [1:0]                        m_axi_rresp,
  input  logic                              m_axi_rlast,
  input  logic                              m_axi_rvalid,
  output logic                              m_axi_rready
);

  generate
    if (EXTERNAL_METADATA) begin : gen_external_metadata_core
      hestia_core_ddr_bbq_extmeta #(
        .PORTS(PORTS),
        .RANK_WIDTH(RANK_WIDTH),
        .SEQ_WIDTH(SEQ_WIDTH),
        .PAYLOAD_WIDTH(PAYLOAD_WIDTH),
        .CELL_COUNT_WIDTH(CELL_COUNT_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .SRAM_CELLS(SRAM_CELLS),
        .BATCH_SIZE(BATCH_SIZE),
        .BATCH_SLOTS(BATCH_SLOTS),
        .PACKET_SLOTS(PACKET_SLOTS),
        .BBQ_BITMAP_WIDTH(BBQ_BITMAP_WIDTH),
        .POLICY_MODE(POLICY_MODE),
        .POLICY_ALPHA_SHIFT(POLICY_ALPHA_SHIFT),
        .POLICY_ALPHA_SHIFT_WIDTH(POLICY_ALPHA_SHIFT_WIDTH),
        .ENABLE_DDR_META_CHECK(ENABLE_DDR_META_CHECK),
        .DDR_BASE_ADDR(DDR_BASE_ADDR)
      ) core (
        .clk(clk),
        .resetn(resetn),
        .enable(enable),
        .cfg_swap_in_threshold(cfg_swap_in_threshold),
        .cfg_swap_out_threshold(cfg_swap_out_threshold),

        .s_pkt_valid(s_pkt_valid),
        .s_pkt_ready(s_pkt_ready),
        .s_pkt_port(s_pkt_port),
        .s_pkt_rank(s_pkt_rank),
        .s_pkt_seq(s_pkt_seq),
        .s_pkt_cell_count(s_pkt_cell_count),
        .s_pkt_payload(s_pkt_payload),

        .dequeue_enable(dequeue_enable),
        .m_pkt_valid(m_pkt_valid),
        .m_pkt_ready(m_pkt_ready),
        .m_pkt_rank(m_pkt_rank),
        .m_pkt_seq(m_pkt_seq),
        .m_pkt_cell_count(m_pkt_cell_count),
        .m_pkt_payload(m_pkt_payload),

        .m_axi_awid(m_axi_awid),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awlock(m_axi_awlock),
        .m_axi_awcache(m_axi_awcache),
        .m_axi_awprot(m_axi_awprot),
        .m_axi_awqos(m_axi_awqos),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bid(m_axi_bid),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready),
        .m_axi_arid(m_axi_arid),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arlock(m_axi_arlock),
        .m_axi_arcache(m_axi_arcache),
        .m_axi_arprot(m_axi_arprot),
        .m_axi_arqos(m_axi_arqos),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rid(m_axi_rid),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),

        .stat_generated(),
        .stat_dequeued(),
        .stat_sram_admit(),
        .stat_hbm_admit(),
        .stat_swap_out(),
        .stat_swap_in(),
        .stat_direct_hbm_dequeue(),
        .stat_drop(),
        .stat_batch_submit(),
        .stat_ddr_write_beats(),
        .stat_ddr_read_beats(),
        .stat_ddr_write_batches(),
        .stat_ddr_read_batches(),
        .dbg_global_sram_occupancy(),
        .dbg_global_hbm_occupancy(),
        .dbg_sram_count_flat(),
        .dbg_hbm_count_flat(),
        .dbg_open_batch_cells(),
        .dbg_ddr_state(),
        .dbg_ddr_wr_error(),
        .dbg_ddr_rd_error()
      );
    end else begin : gen_inline_metadata_core
      hestia_core_ddr_bbq #(
        .PORTS(PORTS),
        .RANK_WIDTH(RANK_WIDTH),
        .SEQ_WIDTH(SEQ_WIDTH),
        .PAYLOAD_WIDTH(PAYLOAD_WIDTH),
        .CELL_COUNT_WIDTH(CELL_COUNT_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .SRAM_CELLS(SRAM_CELLS),
        .BATCH_SIZE(BATCH_SIZE),
        .BATCH_SLOTS(BATCH_SLOTS),
        .PACKET_SLOTS(PACKET_SLOTS),
        .BBQ_BITMAP_WIDTH(BBQ_BITMAP_WIDTH),
        .POLICY_MODE(POLICY_MODE),
        .POLICY_ALPHA_SHIFT(POLICY_ALPHA_SHIFT),
        .POLICY_ALPHA_SHIFT_WIDTH(POLICY_ALPHA_SHIFT_WIDTH),
        .ENABLE_DDR_META_CHECK(ENABLE_DDR_META_CHECK),
        .DDR_BASE_ADDR(DDR_BASE_ADDR)
      ) core (
        .clk(clk),
        .resetn(resetn),
        .enable(enable),
        .cfg_swap_in_threshold(cfg_swap_in_threshold),
        .cfg_swap_out_threshold(cfg_swap_out_threshold),

        .s_pkt_valid(s_pkt_valid),
        .s_pkt_ready(s_pkt_ready),
        .s_pkt_port(s_pkt_port),
        .s_pkt_rank(s_pkt_rank),
        .s_pkt_seq(s_pkt_seq),
        .s_pkt_cell_count(s_pkt_cell_count),
        .s_pkt_payload(s_pkt_payload),

        .dequeue_enable(dequeue_enable),
        .m_pkt_valid(m_pkt_valid),
        .m_pkt_ready(m_pkt_ready),
        .m_pkt_rank(m_pkt_rank),
        .m_pkt_seq(m_pkt_seq),
        .m_pkt_cell_count(m_pkt_cell_count),
        .m_pkt_payload(m_pkt_payload),

        .m_axi_awid(m_axi_awid),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awlock(m_axi_awlock),
        .m_axi_awcache(m_axi_awcache),
        .m_axi_awprot(m_axi_awprot),
        .m_axi_awqos(m_axi_awqos),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bid(m_axi_bid),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready),
        .m_axi_arid(m_axi_arid),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arlock(m_axi_arlock),
        .m_axi_arcache(m_axi_arcache),
        .m_axi_arprot(m_axi_arprot),
        .m_axi_arqos(m_axi_arqos),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rid(m_axi_rid),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),

        .stat_generated(),
        .stat_dequeued(),
        .stat_sram_admit(),
        .stat_hbm_admit(),
        .stat_swap_out(),
        .stat_swap_in(),
        .stat_direct_hbm_dequeue(),
        .stat_drop(),
        .stat_batch_submit(),
        .stat_ddr_write_beats(),
        .stat_ddr_read_beats(),
        .stat_ddr_write_batches(),
        .stat_ddr_read_batches(),
        .dbg_global_sram_occupancy(),
        .dbg_global_hbm_occupancy(),
        .dbg_sram_count_flat(),
        .dbg_hbm_count_flat(),
        .dbg_open_batch_cells(),
        .dbg_ddr_state(),
        .dbg_ddr_wr_error(),
        .dbg_ddr_rd_error()
      );
    end
  endgenerate
endmodule
